title: " "
body:
  - type: textarea
    id: description
    attributes:
      label: Session description
      description: "Just write a few sentences on what the session should be about."
    validations:
      required: true
      
  - type: textarea
    id: audience
    attributes:
      label: Audience
      description: "[Optional] Do you have a specific audience in mind? Is this session suitable for beginners or should people already have experience in the topic? What domain expertise would you love if it could be at the session?"
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        __Thank you for participating! __ :tada:
